version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    network_mode: host

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: singadrive_db
      POSTGRES_USER: ${SINGADRIVE_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${SINGADRIVE_POSTGRES_PASSWORD}
    command: postgres -c listen_addresses=*
    network_mode: host

  flyway:
    network_mode: host
    image: flyway/flyway:latest
    command:
      - "-url=jdbc:postgresql://localhost:5432/singadrive_db"
      - "-user=${SINGADRIVE_POSTGRES_USERNAME}"
      - "-password=${SINGADRIVE_POSTGRES_PASSWORD}"
      - "migrate"
    volumes:
      - ./postgreSQL-migrations:/flyway/sql

  pgadmin:
    network_mode: host
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080

  mongo-express:
    image: mongo-express
    network_mode: host
    environment:
      ME_CONFIG_MONGODB_SERVER: 127.0.0.1
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongo_volume
